services:
  postgres:
    image: postgres-pg-partman:latest
    build:
      context: ./postgres
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
    - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:6.2.21
    volumes:
    - redis_data:/data
    ports:
    - "6379:6379"

  minio:
    image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z
    command:
    - "minio"
    - "server"
    - "/data"
    - "--console-address"
    - ":9001"
    volumes:
    - minio_data:/data
    ports:
    - "9000:9000"
    - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "secretpassword"

  migrate:
    image: quay.io/theauthgear/authgear-server:2026-01-08.0
    env_file:
    - ./env
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command:
    - |
      authgear database migrate up &&
      authgear audit database migrate up &&
      authgear images database migrate up

  migrate-portal:
    image: quay.io/theauthgear/authgear-portal:2026-01-08.0
    env_file:
    - ./env
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command:
    - |
      authgear-portal database migrate up

  nginx:
    image: nginx:stable
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "8010:8010"
    - "3100:3100"

  authgear:
    image: quay.io/theauthgear/authgear-server:2026-01-08.0
    volumes:
    - ./var:/app
    env_file:
    - ./env
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
    - "3000:3000"
    - "3001:3001"
    - "3002:3002"

  authgear-images:
    image: quay.io/theauthgear/authgear-server:2026-01-08.0
    volumes:
    - ./var:/app
    env_file:
    - ./env
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
    - "3004:3004"

  authgear-portal:
    image: quay.io/theauthgear/authgear-portal:2026-01-08.0
    volumes:
    - ./var:/app
    env_file:
    - ./env
    depends_on:
      migrate-portal:
        condition: service_completed_successfully
    ports:
    - "3003:3003"

  authgear-deno:
    image: quay.io/theauthgear/authgear-deno:git-27a7ae9a2b70
    ports:
    - "8090:8090"

volumes:
  redis_data:
    driver: local
  db_data:
    driver: local
  minio_data:
    driver: local
